name: Test Workflow
defaults:
  run:
    shell: bash -leo pipefail {0}
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
permissions:
  contents: read
  checks: write
jobs:
  parser-results:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: 'test*.xml'
          check_name: Test Report
